// @flow

export const INIT_FIREBASE = 'INIT_FIREBASE'

export const GOOGLE_SIGNIN = 'GOOGLE_SIGNIN'
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS'
export const GOOGLE_SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE'

export const RESTORE_SESSION = 'RESTORE_SESSION'
export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS'
export const RESTORE_SESSION_FAILURE = 'RESTORE_SESSION_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const SEND_MESSAGE = 'SEND_MESSAGE'
